apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-booking
  template:
    metadata:
      labels:
        app: ticket-booking
    spec:
      containers:
      - name: ticket-booking
        image: jashwanth00/ticket-booking:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
